### ISSUE TITLE
add: tracking screens automaticly with mixpanel

### ISSUE THREAD

**Issue by tiagosavioli** [Circle-Company/Circle-App#28]
- [x] Install Mixpanel sdk
- [x] Create tracking context and export mixpanel
- [x] config mixpanel token and pass to initializer + initial params
- [x] set identifyer and add user informations
